---
- name: jenkins slave setup using ansible
  hosts: jenkins_slave
  become: true
  tasks:
    - name: Install Java 17
      ansible.builtin.dnf:
        name: java-17-amazon-corretto
        state: present
    - name: Install maven
      get_url: 
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz 