---
- name: jenkins slave setup using ansible
  hosts: jenkins-slave
  become: true
  tasks:
    - name: install java 17
      ansible.builtin.dnf:
        name: java-17-amazon-corretto
        state: present
    - name: Install Maven
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        dest: /opt
    - name: extact maven pkg 
      unarchive:
        src: /opt/apache-maven-3.9.9-bin.tar.gz
        dest: /opt
        remote_src: yes
    - name: install git
      yum:
        name: git
        state: present  
      tags: install_git
    - name: check git version
      shell: git --version 
      tags: install_git
      register: git_version
    - name: print git version
      debug: 
        msg: "{{ git_version.stdout }}"
      tags: install_git         